### ISSUE TITLE
Hi about your test version and the stable versions

### ISSUE THREAD

**Issue by egydoctor2010** [N-X-T/TrickyStore#1]
Hi bro, thanks for your great efforts
I am able to pass strong integrity on Galaxy s9 plus, android 10
On your first unpublished version which was 
Tricky-Store-v1.0.3_Android11-_TEST
then after your 2 stable releases with one does not support tee broken and the other support tee broken, I cannot pass any more
So any help
I can provide logs you need.

**Comment by N-X-T** [comment]
that's crazy :v
Tricky-Store-v1.0.3_Android11-_TEST same code with V1.0.3  not support tee broken.
Maybe fingerprint or keybox is banned
use lastest debug and send me log

**Comment by egydoctor2010** [comment]
Hi my device suppose to have intact tee
 I was using test version, and add packages without ! To target txt file And it was working good
Then after your 1st version it was meeting only basic integrity with the same finger print and keybox used in test version which passed strong with test version, then I tried to add ! To packages and also meet basic
Then with second release that support tee broken, I meet basic also and failed to get strong with packages in target txt file added without !.
While I was searching in xda I found one person with OnePlus phone sending report which was normal and some one advised him to add ! And try
I tried also with the last version that support tee broken and this time I get strong integrity again
Any way thanks for support and thanks for all your efforts
